# ........................................................................
#
#  fgarcia,acaldero@hinojo.datsi.fi.upm.es
#
# ........................................................................



#--------------------------
# 1.- Native configuration
#--------------------------

CC             = gcc
LIB_PATH       = -L/usr/lib
INCLUDE_PATH   = -I./ -I./../../src/ -I./../../include/
SOURCE_PATH    =   .
CFLAGS         = -g -Wall -D__LINUX__ -D_REENTRANT -DPOSIX_THREADS
LIBLINK        = -lpthread -lz ../../lib/liblzrw3.a


#--------------------------
# 2.- library object
#--------------------------

LIBPATH   = ../../lib/
LIBNAME   = libmpi.a
OBJETOS   = \
            $(SOURCE_PATH)/ping.o


#--------------------------
# 3.- compilation rules
#--------------------------

all:    init    ping
refast: clean   ping
fast:   ping

ping: $(OBJETOS)
	@echo "   Building ping :"
	@echo "     ping.exe ..."
	@$(CC)  $(CFLAGS) -o ping.exe $(OBJETOS) $(LIBPATH)/$(LIBNAME) $(LIBLINK)


init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    examples" 
	@echo "   ----------"
	@echo "" 
	@echo "   Computer  :"
	@echo "     "`uname -a` 
	@echo "   Options   :"
	@echo "     "$(CFLAGS)
	@echo "   Directory :"
	@echo "     "$(INCLUDE_PATH)
	@echo "   Compiling :"

%.o: %.c
	@echo "     $< ..." 
	@$(CC)  $(CFLAGS) $(INCLUDE_PATH) -c $< -o $@ 


clean: 
	@echo "   Removing trash..."
	@rm -fr $(OBJETOS) ./ping.exe
	@echo "   Trash succesfully removed !."


# ........................................................................

