# ........................................................................
#
#  fgarcia,acaldero@hinojo.datsi.fi.upm.es
#
# ........................................................................



#--------------------------
# 1.- Native configuration
#--------------------------

MAKE          = make
SRCDIR        = .
DIR           = ping  hello


#--------------------------
# 2.- library object
#--------------------------



#--------------------------
# 3.- compilation rules
#--------------------------

all:    init  compo  
fast:         compo 


init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    examples" 
	@echo "   ----------" 
	@echo "" 

compo:
	@set -e;  for i in $(DIR);   do $(MAKE) -C $$i -f Makefile.linux fast;  done


clean: 
	@echo "   Removing trash..."
	@set -e;  for i in $(DIR);   do $(MAKE) -C $$i -f Makefile.linux clean;  done
	@echo "   Trash succesfully removed !."


# ........................................................................

