#---------------------- partest' MAKEFILE -------------------- 
 



# --- 1.- Opciones del sistema base ---

#-----------------------
# Constantes en SP2
#-----------------------
 
CC            = cc_r
LIB_PATH      = -L/usr/lib
SOURCE_PATH   = .
CFLAGS        = -g -I./ -I./../../../../src/ -I./../../../../include/ -D__SP2__ 
LIBLINK       =


# --- 2.- Perfil de la libreria -------

LIB_PATH  = ../../../../lib/
LIBNAME   = libmpi.a
OBJETOS   = \
            $(SOURCE_PATH)/partest.o



 
#--------------------------
# Reglas de compilacion ...
#-------------------------- 

all:    init    partest
refast: clean   partest
fast:   partest

partest: $(OBJETOS)
	@echo "   Building partest :"
	@echo "     partest.sp2.xmp ..."
	@$(CC)  $(CFLAGS) -o partest.sp2.xmp  $(SOURCE_PATH)/partest.o $(LIB_PATH)/$(LIBNAME) $(LIBLINK)


init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    partest" 
	@echo "   ---------"
	@echo "" 
	@echo "   Computer  :"
	@echo "     "`uname -a` 
	@echo "   Options   :"
	@echo "     "$(CFLAGS)
	@echo "   Directory :"
	@echo "     "$(INCLUDE_PATH)
	@echo "   Compiling :"

%.o: %.c
	@echo "     $< ..." 
	@$(CC)  $(CFLAGS) $(INCLUDE_PATH) -c $< -o $@ 


clean: 
	@echo "   Removing trash..."
	@rm -fr $(OBJETOS) ./partest.sp2.xmp
	@echo "   Trash succesfully removed !."




# ---------------------- partest' MAKEFILE -------------------- 

