#---------------------- scatter' MAKEFILE -------------------- 
 


#--------------------------
# Sistema base
#-------------------------- 

CC             = mpicc
LIB_PATH       = -L/usr/lib
INCLUDE_PATH   = -I./
SOURCE_PATH    = .
CFLAGS         = -Wall
LIBLINK        = -lpthread



#--------------------------
# Objetos
#-------------------------- 

OBJETOS   = \
            $(SOURCE_PATH)/scatter.o


 
#--------------------------
# Reglas de compilacion ...
#-------------------------- 

all:    init    scatter
refast: clean   scatter
fast:   scatter

scatter: $(OBJETOS)
	@echo "   Building scatter :"
	@echo "     scatter.linux.mpich ..."
	@$(CC)  $(CFLAGS) -o scatter.linux.mpich $(OBJETOS) $(LIBLINK)


init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    scatter" 
	@echo "   ---------"
	@echo "" 
	@echo "   Computer  :"
	@echo "     "`uname -a` 
	@echo "   Options   :"
	@echo "     "$(CFLAGS)
	@echo "   Directory :"
	@echo "     "$(INCLUDE_PATH)
	@echo "   Compiling :"

%.o: %.c
	@echo "     $< ..." 
	@$(CC)  $(CFLAGS) $(INCLUDE_PATH) -c $< -o $@ 


clean: 
	@echo "   Removing trash..."
	@rm -fr $(OBJETOS) ./scatter.linux.mpich
	@echo "   Trash succesfully removed !."



# ---------------------- scatter' MAKEFILE -------------------- 

