#---------------------- ping' MAKEFILE -------------------- 
 


#--------------------------
# Sistema base
#-------------------------- 

CC             = mpicc
LIB_PATH       = -L/usr/lib
INCLUDE_PATH   = -I./
SOURCE_PATH    = .
CFLAGS         = -Wall
LIBLINK        = -lpthread



#--------------------------
# Objetos
#-------------------------- 

OBJETOS   = \
            $(SOURCE_PATH)/ping.o


 
#--------------------------
# Reglas de compilacion ...
#-------------------------- 

all:    init    ping
refast: clean   ping
fast:   ping

ping: $(OBJETOS)
	@echo "   Building ping :"
	@echo "     ping.linux.mpich ..."
	@$(CC)  $(CFLAGS) -o ping.linux.mpich $(OBJETOS) $(LIBLINK)


init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    ping  " 
	@echo "   ------"
	@echo "" 
	@echo "   Computer  :"
	@echo "     "`uname -a` 
	@echo "   Options   :"
	@echo "     "$(CFLAGS)
	@echo "   Directory :"
	@echo "     "$(INCLUDE_PATH)
	@echo "   Compiling :"

%.o: %.c
	@echo "     $< ..." 
	@$(CC)  $(CFLAGS) $(INCLUDE_PATH) -c $< -o $@ 


clean: 
	@echo "   Removing trash..."
	@rm -fr $(OBJETOS) ./ping.linux.mpich
	@echo "   Trash succesfully removed !."



# ---------------------- ping' MAKEFILE -------------------- 

