# ........................................................................
#
#  fgarcia,acaldero@hinojo.datsi.fi.upm.es
#
# ........................................................................



#--------------------------
# 1.- Native configuration
#--------------------------

MAKE          = make
SRCDIR        = .
DIR           = base  map


#--------------------------
# 2.- library object
#--------------------------



#--------------------------
# 3.- compilation rules
#--------------------------

all:    init  compo
fast:         compo


init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    xmp_tcp" 
	@echo "   ---------" 
	@echo "" 

compo:
	@set -e;  for i in $(DIR);   do cd $$i; $(MAKE) -f Makefile.sp2 fast; cd ..; done



clean: 
	@echo "   Removing trash..."
	@set -e;  for i in $(DIR);   do cd $$i; $(MAKE) -f Makefile.sp2 clean; cd ..; done
	@echo "   Trash succesfully removed !."


# ........................................................................

