#---------------------- test_run' MAKEFILE -------------------- 
 



# --- 1.- Opciones del sistema base ---

CC            = gcc
LIB_PATH      = -L/usr/lib
INCLUDE_PATH   = -I./ -I./../../ -I./../../include
SOURCE_PATH   =   .
CFLAGS        = -g -Wall -D__SUNOS__ -DSOLARIS
LIBLINK       = -lsocket -lnsl -lposix4 -lpthread



# --- 2.- Perfil de la libreria -------

OBJETOS_RUN    = \
            $(SOURCE_PATH)/test_run.o

EXE_NAME       = \
            test_run.exe
EXE_PATH       = \
            $(SOURCE_PATH)/../../bin/


 
#--------------------------
# Reglas de compilacion ...
#-------------------------- 

all:     init   test_run 
refast:  clean  test_run
fast:           test_run

test_run: $(OBJETOS_RUN)
	@echo "   Building test_run ..."
	@$(CC)  $(CFLAGS) -o $(EXE_PATH)/$(EXE_NAME)  $(OBJETOS_RUN) $(LIBLINK)


init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    test_run" 
	@echo "   ----------"
	@echo "" 
	@echo "   Computer  :"
	@echo "     "`uname -a` 
	@echo "   Options   :"
	@echo "     "$(CFLAGS)
	@echo "   Directory :"
	@echo "     "$(INCLUDE_PATH)
	@echo "   Compiling :"

%.o: %.c
	@echo "     $< ..." 
	@$(CC)  $(CFLAGS) $(INCLUDE_PATH) -c $< -o $@ 


clean: 
	@echo "   Removing trash..."
	@rm -fr $(OBJETOS_RUN) $(EXE_PATH)/$(EXE_NAME)
	@echo "   Trash succesfully removed !."




# ---------------------- test_run' MAKEFILE -------------------- 

