# ------------------------------ MAKEFILE -----------------------
 


# --- 1.- Operating system options ---

CC            = gcc
LIB_PATH      = -L/usr/lib
INCLUDE_PATH  = -I./ -I../../../../src/ -I../../../../include
SOURCE_PATH   = .
CFLAGS        = -g -Wall -D__SUNOS__ -D_REENTRANT -DPOSIX_THREADS  -D__MEMORY_DEBUG__  -DSOLARIS
LIBLINK       = -lpthread -lsocket -lnsl -lposix4 -lpthread



# --- 2.- Libraries profiles -------

LIB_PATH  = ../../../../lib/
LIBNAME   = libmpi.a
TEST_OBJ  = \
            $(SOURCE_PATH)/c_basic.o

 

# --- 3.- Compilation rules -------

all:    init  $(TEST_OBJ)  test
fast:         $(TEST_OBJ)  test


init:
	@echo "" 
	@echo "    test" 
	@echo "   ------" 
	@echo "" 
	@echo "   Options   :"
	@echo "     "$(CFLAGS)
	@echo "   Directory :"
	@echo "     "$(INCLUDE_PATH)
	@echo "   Compiling :"

%.o: %.c
	@echo "     $< ..." 
	@$(CC)  $(CFLAGS) $(INCLUDE_PATH) -c $< -o $@ 

test:
	@echo "   Building test :"
	@echo "     c_basic.exe ..."
	@$(CC)  $(CFLAGS) -o ./c_basic.exe c_basic.o $(LIB_PATH)/$(LIBNAME) $(LIBLINK)

clean: 
	@echo "   Removing trash..."
	@rm -fr $(TEST_OBJ) 
	@rm -fr ./c_basic.exe
	@echo "   Trash succesfully removed !."



# ------------------------------ MAKEFILE -----------------------

