# ------------------------------ MAKEFILE ----------------------- 
 


# --- 1.- Opciones del sistema base ---

MAKE          = make
SRCDIR        = .
LIB_PATH      = -L/usr/lib
INCLUDE_PATH  = -I./
DIR           = test_run  test_reduce  xmp_run  mpi_exec


# --- 2.- Reglas de compilacion -------

all:    init  compo
fast:         compo


init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    Utilities" 
	@echo "   -----------" 
	@echo "" 

compo:
	@set -e;  for i in $(DIR);   do cd $$i; $(MAKE) -f Makefile.sunos fast; cd ..; done



clean: 
	@echo "   Removing trash..."
	@set -e;  for i in $(DIR);   do cd $$i; $(MAKE) -f Makefile.sunos clean; cd ..; done
	@echo "   Trash succesfully removed !."




# ----------------------------- END MAKEFILE -------------------- 

