# ........................................................................
#
#  fgarcia,acaldero@hinojo.datsi.fi.upm.es
#
# ........................................................................



#--------------------------
# 1.- Native configuration
#--------------------------

CC            = cc_r
LIB_PATH      = -L/usr/lib
SOURCE_PATH   =   .
CFLAGS        = -g -I./ -I./../../src/ -I./../../include/ -D__SP2__
LIBLINK       = -lpthread -lbsd -lz ../../lib/liblzrw3.a


#--------------------------
# 2.- library object
#--------------------------

LIBPATH   = ../../lib/
LIBNAME   = libmpi.a
OBJETOS   = \
            $(SOURCE_PATH)/hello_world.o


#--------------------------
# 3.- compilation rules
#--------------------------
 
all:    init    hello_world
refast: clean   hello_world
fast:   hello_world

hello_world: $(OBJETOS)
	@echo "   Building hello_world :"
	@echo "     hello_world.exe ..."
	@$(CC)  $(CFLAGS) -o hello_world.exe $(OBJETOS) $(LIBLINK) $(LIBPATH)/$(LIBNAME)


init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    examples" 
	@echo "   ----------"
	@echo "" 
	@echo "   Computer  :"
	@echo "     "`uname -a` 
	@echo "   Options   :"
	@echo "     "$(CFLAGS)
	@echo "   Directory :"
	@echo "     "$(INCLUDE_PATH)
	@echo "   Compiling :"

%.o: %.c
	@echo "     $< ..." 
	@$(CC)  $(CFLAGS) $(INCLUDE_PATH) -c $< -o $@ 


clean: 
	@echo "   Removing trash..."
	@rm -fr $(OBJETOS) ./hello_world.exe
	@echo "   Trash succesfully removed !."


# ........................................................................

