#---------------------- bcast' MAKEFILE -------------------- 
 


#--------------------------
# Sistema base
#-------------------------- 

CC             = mpicc
LIB_PATH       = -L/usr/lib
INCLUDE_PATH   = -I./
SOURCE_PATH    = .
CFLAGS         = -Wall
LIBLINK        = -lpthread



#--------------------------
# Objetos
#-------------------------- 

OBJETOS   = \
            $(SOURCE_PATH)/bcast.o


 
#--------------------------
# Reglas de compilacion ...
#-------------------------- 

all:    init    bcast
refast: clean   bcast
fast:   bcast

bcast: $(OBJETOS)
	@echo "   Building bcast :"
	@echo "     bcast.linux.mpich ..."
	@$(CC)  $(CFLAGS) -o bcast.linux.mpich $(OBJETOS) $(LIBLINK)


init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    bcast" 
	@echo "   -------"
	@echo "" 
	@echo "   Computer  :"
	@echo "     "`uname -a` 
	@echo "   Options   :"
	@echo "     "$(CFLAGS)
	@echo "   Directory :"
	@echo "     "$(INCLUDE_PATH)
	@echo "   Compiling :"

%.o: %.c
	@echo "     $< ..." 
	@$(CC)  $(CFLAGS) $(INCLUDE_PATH) -c $< -o $@ 


clean: 
	@echo "   Removing trash..."
	@rm -fr $(OBJETOS) ./bcast.linux.mpich
	@echo "   Trash succesfully removed !."



# ---------------------- bcast' MAKEFILE -------------------- 

