#---------------------- gather' MAKEFILE -------------------- 
 



# --- 1.- Opciones del sistema base ---

#-----------------------
# Constantes en SP2
#-----------------------
 
CC            = mpcc
LIB_PATH      = -L/usr/lib
SOURCE_PATH   = .
CFLAGS        = -g -I./ 
LIBLINK       =



# --- 2.- Perfil de la libreria -------

OBJETOS   = \
            $(SOURCE_PATH)/gather.o



 
#--------------------------
# Reglas de compilacion ...
#-------------------------- 

all:    init    gather
refast: clean   gather
fast:   gather

gather: $(OBJETOS)
	@echo "   Building gather :"
	@echo "     gather.sp2.native ..."
	@$(CC)  $(CFLAGS) -o gather.sp2.native $(OBJETOS) $(LIBLINK)


init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    gather" 
	@echo "   --------"
	@echo "" 
	@echo "   Computer  :"
	@echo "     "`uname -a` 
	@echo "   Options   :"
	@echo "     "$(CFLAGS)
	@echo "   Directory :"
	@echo "     "$(INCLUDE_PATH)
	@echo "   Compiling :"

%.o: %.c
	@echo "     $< ..." 
	@$(CC)  $(CFLAGS) $(INCLUDE_PATH) -c $< -o $@ 


clean: 
	@echo "   Removing trash..."
	@rm -fr $(OBJETOS) ./gather.sp2.native
	@echo "   Trash succesfully removed !."




# ---------------------- gather' MAKEFILE -------------------- 

