# ------------------------------ MAKEFILE -----------------------
 


# --- 1.- Operating system options ---

CC             = gcc
LIB_PATH       = -L/usr/lib
INCLUDE_PATH   = -I./ -I../../../../../src/ -I../../../../include
SOURCE_PATH    = .
CFLAGS         = -g -Wall  -D__LINUX__ -D__SWITCH__ -D_REENTRANT -DPOSIX_THREADS -D__MEMORY_DEBUG__  
LIBLINK        = -lpthread



# --- 2.- Libraries profiles -------

TEST_OBJ  = \
            $(SOURCE_PATH)/server.o  \
            $(SOURCE_PATH)/client.o

 

# --- 3.- Compilation rules -------

all:    init  $(TEST_OBJ)  test
fast:         $(TEST_OBJ)  test


init:
	@echo "" 
	@echo "    test" 
	@echo "   ------" 
	@echo "" 
	@echo "   Options   :"
	@echo "     "$(CFLAGS)
	@echo "   Directory :"
	@echo "     "$(INCLUDE_PATH)
	@echo "   Compiling :"

%.o: %.c
	@echo "     $< ..." 
	@$(CC)  $(CFLAGS) $(INCLUDE_PATH) -c $< -o $@ 

test:
	@echo "   Building test :"
	@echo "     server.exe ..."
	@$(CC)  $(CFLAGS) -o ./server.exe server.o $(LIB_PATH)/$(LIBNAME) $(LIBLINK)
	@echo "     client.exe ..."
	@$(CC)  $(CFLAGS) -o ./client.exe client.o $(LIB_PATH)/$(LIBNAME) $(LIBLINK)


clean: 
	@echo "   Removing trash..."
	@rm -fr $(TEST_OBJ) 
	@rm -fr ./server.exe
	@rm -fr ./client.exe
	@echo "   Trash succesfully removed !."



# ------------------------------ MAKEFILE -----------------------

