#---------------------- reduce' MAKEFILE -------------------- 
 


#--------------------------
# Sistema base
#-------------------------- 

CC             = mpicc
LIB_PATH       = -L/usr/lib
INCLUDE_PATH   = -I./
SOURCE_PATH    = .
CFLAGS         = -Wall
LIBLINK        = -lpthread



#--------------------------
# Objetos
#-------------------------- 

OBJETOS   = \
            $(SOURCE_PATH)/reduce.o


 
#--------------------------
# Reglas de compilacion ...
#-------------------------- 

all:    init    reduce
refast: clean   reduce
fast:   reduce

reduce: $(OBJETOS)
	@echo "   Building reduce :"
	@echo "     reduce.linux.mpich ..."
	@$(CC)  $(CFLAGS) -o reduce.linux.mpich $(OBJETOS) $(LIBLINK)


init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    reduce" 
	@echo "   --------"
	@echo "" 
	@echo "   Computer  :"
	@echo "     "`uname -a` 
	@echo "   Options   :"
	@echo "     "$(CFLAGS)
	@echo "   Directory :"
	@echo "     "$(INCLUDE_PATH)
	@echo "   Compiling :"

%.o: %.c
	@echo "     $< ..." 
	@$(CC)  $(CFLAGS) $(INCLUDE_PATH) -c $< -o $@ 


clean: 
	@echo "   Removing trash..."
	@rm -fr $(OBJETOS) ./reduce.linux.mpich
	@echo "   Trash succesfully removed !."



# ---------------------- reduce' MAKEFILE -------------------- 

