#---------------------- fpu' MAKEFILE -------------------- 
 



# --- 1.- Opciones del sistema base ---

#-----------------------
# Constantes en LINUX
#-----------------------
 
CC             = gcc
LIB_PATH       = -L/usr/lib
INCLUDE_PATH   = -I./ -I./../../../src/ -I./../../../include
SOURCE_PATH    =   .
CFLAGS         = -g -Wall -D__LINUX__ -D_REENTRANT -DPOSIX_THREADS 
LIBLINK        = -lpthread


# --- 2.- Perfil de la libreria -------

OBJETOS   = \
            $(SOURCE_PATH)/fpu.o



 
#--------------------------
# Reglas de compilacion ...
#-------------------------- 

all:    init    fpu
refast: clean   fpu
fast:   fpu

fpu: $(OBJETOS)
	@echo "   Building fpu :"
	@echo "     fpu.linux ..."
	@$(CC)  $(CFLAGS) -o fpu.linux $(OBJETOS) $(LIBLINK)


init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    fpu" 
	@echo "   -----"
	@echo "" 
	@echo "   Computer  :"
	@echo "     "`uname -a` 
	@echo "   Options   :"
	@echo "     "$(CFLAGS)
	@echo "   Directory :"
	@echo "     "$(INCLUDE_PATH)
	@echo "   Compiling :"

%.o: %.c
	@echo "     $< ..." 
	@$(CC)  $(CFLAGS) $(INCLUDE_PATH) -c $< -o $@ 


clean: 
	@echo "   Removing trash..."
	@rm -fr $(OBJETOS)  ./fpu.linux
	@echo "   Trash succesfully removed !."




# ---------------------- fpu' MAKEFILE -------------------- 

