# ------------------------------ MAKEFILE ----------------------- 
 


# --- 1.- Opciones del sistema base ---

CC            = gcc
MAKE          = make
SRCDIR        = .
DIR           = ping  barrier  bcast  reduce  scatter  gather  wtime



# --- 2.- Reglas de compilacion -------

all:    init  compo
fast:         compo


init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    MPI integrity" 
	@echo "   ---------------" 
	@echo "" 

compo:
	@set -e;  for i in $(DIR);  do cd $$i; $(MAKE) -f Makefile.sp2   fast; cd ..; done



clean: 
	@echo "   Removing trash..."
	@set -e;  for i in $(DIR);  do cd $$i; $(MAKE) -f Makefile.sp2   clean; cd ..; done
	@echo "   Trash succesfully removed !."



# ----------------------------- END MAKEFILE -------------------- 

