# ........................................................................
#
#  fgarcia,acaldero@hinojo.datsi.fi.upm.es
#
# ........................................................................



#--------------------------
# 1.- Native configuration
#--------------------------

CC            = gcc
MAKE          = make
SRCDIR        =   .
LIB_PATH      = -L/usr/lib
INCLUDE_PATH  = -I./
LIBLINK       = -lpthread -lsocket -lnsl
DIR           = base  console  mp 


#--------------------------
# 2.- library object
#--------------------------

LIB_PATH  = ./../lib/
LIBNAME   = libmpi.a
NS_PATH   = ./../bin/
NSNAME    = ns.exe


#--------------------------
# 3.- compilation rules
#--------------------------

all:    init  compo  mpi.a  ns.exe
fast:         compo  mpi.a  ns.exe


ns.exe:
	@echo "   Building NameServer :"
	@echo "     ns.exe ..."
	@$(CC)  $(CFLAGS) -o $(NS_PATH)/$(NSNAME) $(LIB_PATH)/$(LIBNAME) $(LIBLINK)

mpi.a:
	@echo "   Building library :"
	@echo "     libmpi.a ..."
	@ar -rc $(LIB_PATH)/$(LIBNAME)
	@ar -rs $(LIB_PATH)/$(LIBNAME) `find base console mp -name "*.o" -print`

init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    MiMPI" 
	@echo "   -------"
	@echo "" 

compo:
	@set -e;  for i in $(DIR);   do cd $$i; $(MAKE) -f Makefile.sunos fast; cd ..; done



clean: 
	@echo "   Removing trash..."
	@set -e;  for i in $(DIR);   do cd $$i; $(MAKE) -f Makefile.sunos clean; cd ..; done
	@rm -fr $(NS_PATH)/$(NSNAME)
	@rm -fr $(LIB_PATH)/$(LIBNAME)
	@echo "   Trash succesfully removed !."


# ........................................................................

