#---------------------- ping' MAKEFILE -------------------- 
 



# --- 1.- Opciones del sistema base ---

#-----------------------
# Constantes en SP2
#-----------------------
 
MPICH_MPL_BIN=/prod/mpich/lib/rs6000/ch_mpl

CC            =  $(MPICH_MPL_BIN)/mpicc
LIB_PATH      = -L/usr/lib
SOURCE_PATH   =   .
CFLAGS        = -g -I./
LIBLINK       =



# --- 2.- Perfil de la libreria -------

OBJETOS   = \
            $(SOURCE_PATH)/ping.o



 
#--------------------------
# Reglas de compilacion ...
#-------------------------- 

all:    init    ping
refast: clean   ping
fast:   ping

ping: $(OBJETOS)
	@echo "   Building ping :"
	@echo "     ping.sp2.mpich ..."
	@$(CC)  $(CFLAGS) -o ping.sp2.mpich $(OBJETOS) $(LIBLINK)


init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    ping  " 
	@echo "   ------"
	@echo "" 
	@echo "   Computer  :"
	@echo "     "`uname -a` 
	@echo "   Options   :"
	@echo "     "$(CFLAGS)
	@echo "   Directory :"
	@echo "     "$(INCLUDE_PATH)
	@echo "   Compiling :"

%.o: %.c
	@echo "     $< ..." 
	@$(CC)  $(CFLAGS) $(INCLUDE_PATH) -c $< -o $@ 


clean: 
	@echo "   Removing trash..."
	@rm -fr $(OBJETOS) ./ping.sp2.mpich
	@echo "   Trash succesfully removed !."




# ---------------------- ping' MAKEFILE -------------------- 

